server:
  port: 7979

spring:
    application:
        name: halms-api-gateway

    cloud:
      gateway:
        routes:
          - id: appointment-service
            uri: http://localhost:8081
            predicates:
              - Path=/appointments/**